version: 2.1

jobs:
  envar1: 
    parameters: 
      new_prompt: 
        type: env_var_name 
        default: prompt
    executor: base
    steps: 
      - run: 
          name: Check envar
          command: |
            echo ${<< parameters.new_prompt >>}
  # envar2:
  #   executor: base 
  #   steps: 
  #     - run: 
  #         name: Check envar
  #         command: |
  #           new_prompt=$prompt
  #           echo $new_prompt

executors:
  base: 
    docker: 
      - image: cimg/base:stable

workflows:
  test:
    jobs: 
      - envar1
      - envar1: 
          new_prompt: prompt2
      # - envar2
