version: 2.1

workflows:
  main:
    unless: << pipeline.parameters.nightly >>
    jobs:
      - the_rest
  nightly_tests:
    when: << pipeline.parameters.nightly >>
    jobs:
      - test

jobs:
  test:
    executor: base
    steps:
      - checkout
  the_rest:
    executor: base
    steps:
      - checkout 

executors:
  base:
    docker:
      - image: cimg/base:stable

parameters:
  nightly:
    type: boolean
    default: false