version: 2.1
  
jobs:
  test:
    executor: runner
    steps:
      - run:
          name: run vmstat commands
          command: |
            while true; do
              sleep 5
              printf "\n\n$(date)\n"
              echo "memory usage:"
              vmstat 1 3 -a -S M -w -t
              echo "======"
              echo "CPU Usage: "$[100-$(vmstat 1 2|tail -1|awk '{print $15}')]"%"
              echo "======"
            done
      # - run:
      #     name: Profile CPU and memory every 5s (background)
      #     command: |
      #       while true; do
      #         sleep 5
      #         printf "\n\n$(date)\n"
      #         top -b -c -n 1
      #         echo "======"
      #         echo "CPU Usage: "$[100-$(vmstat 1 2|tail -1|awk '{print $15}')]"%"
      #         echo "======"
      #       done
      #     background: true
          
      - checkout
      - run: sudo apt-get install stress
      - run: sudo stress --cpu 1 --timeout 20

workflows:
  main:
    jobs:
      - test

executors:
  runner:
    docker:
      - image: cimg/base:stable
    resource_class: ryanpedersen/container-runner-local

# VS Code Extension Version: 1.0.0