version: 2.1

setup: true

# orbs:
#   continuation: circleci/continuation@0.3.1 

jobs:
  generate-config:
    executor: base
    steps:
      - checkout
      - run: 
          name: check tags
          command: |
            echo "PR Number is ${CIRCLE_PULL_REQUEST##*/}"

            FINAL_CONFIG_PATH=".circleci/continuation.yml"

            LABELS=`curl \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues/${CIRCLE_PULL_REQUEST##*/}/labels`

            echo "{" > tmp.json
            ISSUE_CALL=`echo $LABELS | jq -c '.[]'`

            if [[ -z ${CIRCLE_PULL_REQUEST} ]]; then
              FINAL_CONFIG_PATH=".circleci/continuation.yml"
              echo "" >> tmp.json 
              echo "config path"
            elif [[ -z ${ISSUE_CALL} ]]; then
              echo "no labels on this issue"
              echo ""no-issue": true," >> tmp.json 
              FINAL_CONFIG_PATH=".circleci/tags/tag.yml"
            else
              echo "labels on this issue"
              echo $ISSUE_CALL | while read i; do 
                echo $i | jq '.name' | while read x; do
                  echo ""$x": true," >> tmp.json 
                done
                  sed -i.bak '$ s/.$//' tmp.json
              done
              FINAL_CONFIG_PATH=".circleci/tags/tag.yml"
            fi
            echo "}" >> tmp.json

            echo "===the json file==="
            cat tmp.json
            echo "==================="
            rm -rf tmp.json.bak
            echo "here is final config pagh $FINAL_CONFIG_PATH"

            jq -n\
              --arg continuation "$CIRCLE_CONTINUATION_KEY" \
              --arg config "$(cat $FINAL_CONFIG_PATH)" \
              --arg params "$(cat tmp.json)" \
              '{"continuation-key": $continuation, "configuration": $config, "parameters": $params}' | tee /tmp/continue-body.json
            
            curl --request POST \
              --url https://circleci.com/api/v2/pipeline/continue \
              --header 'content-type: application/json' \
              --data-binary @/tmp/continue-body.json

workflows:
  setup-workflow:
    jobs:
      - generate-config

executors:
  base:
    docker:
      - image: cimg/base:stable

# VS Code Extension Version: 1.0.0