version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1 

jobs:
  generate-config:
    executor: base
    steps:
      - checkout
      - run: 
          name: check tags
          command: |
            echo ${CIRCLE_PULL_REQUEST##*/}

            CONFIG_PATH=".circleci/continuation.yml"

            LABELS=`curl \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues/${CIRCLE_PULL_REQUEST##*/}/labels`
            LABEL_NAME=`echo $LABELS | jq -c '.[]' | jq '.name'`
            echo $LABEL_NAME

            if [ $LABEL_NAME = "enhancement" ]; then
              CONFIG_PATH=".circleci/tags/tag.yml"
              echo 'export OUTSIDE="some string"' >> "$BASH_ENV"
            fi

            echo 'export CONFIG_PATH="$CONFIG_PATH"' >> "$BASH_ENV"
            echo 'export FINAL_CONFIG_PATH="$CONFIG_PATH"' >> "$BASH_ENV"
            source "$BASH_ENV"
            echo $CONFIG_PATH
            echo $FINAL_CONFIG_PATH
            echo "anything $OUTSIDE"
      - continuation/continue:
            configuration_path: $CONFIG_PATH

workflows:
  setup-workflow:
    jobs:
      - generate-config

executors:
  base:
    docker:
      - image: cimg/base:stable

# VS Code Extension Version: 1.0.0