version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  generate-config:
    executor: base
    steps:
      - checkout
      - run: 
          name: Generate continuation config file
          command: |
            TASK_QUERY=`curl -X GET https://runner.circleci.com/api/v2/tasks?resource-class=ryanpedersen/container-agent -H 'Circle-Token: ${ACCESS_TOKEN}' | jq .unclaimed_task_count`
            echo $TASK_QUERY
            
            ./scripts/generate-config "runner"
      - continuation/continue:
          configuration_path: configs/generated_config.yml
workflows:
  setup-workflow:
    jobs:
      - generate-config

executors:
  base:
    docker:
      - image: cimg/base:stable