version: 2.1
  
jobs:
  test_runner:
    executor: runner
    steps:
      - run: |
          lscpu
      - run: |
          cat /sys/fs/cgroup/cpu.stat
          cat /sys/fs/cgroup/memory.stat

      - run:
          name: run usage commands
          command: |
            while true; do
              sleep 5
              echo "Mem Usage: "$(free | grep Mem | awk '{print $3/$2 * 100.0}')"%"
              echo "======"
              echo "CPU Usage: "$[100-$(vmstat 1 2|tail -1|awk '{print $15}')]"%"
              echo "======"
            done
          background: true
      - run:
          name: Profile CPU and memory every 5s (background)
          command: |
            while true; do
              sleep 5
              printf "\n\n$(date)\n"
              top -b -c -n 1
              echo "======"
            done
          background: true

      - checkout
      - run: 
          name: install some packages
          command: | 
            npm init -y
            npm i express cors
      - run: sleep 45
      - run: |
          cat /sys/fs/cgroup/cpu.max
          cat /sys/fs/cgroup/memory.max
          cat /sys/fs/cgroup/memory.high
  test_cloud:
    executor: cloud
    steps:
      - run: |
          lscpu
      - run: |
          cat /sys/fs/cgroup/cpu/cpuacct.usage
          cat /sys/fs/cgroup/memory/memory.usage_in_bytes

      - run:
          name: run usage commands
          command: |
            while true; do
              sleep 5
              echo "Mem Usage: "$(free | grep Mem | awk '{print $3/$2 * 100.0}')"%"
              echo "======"
              echo "CPU Usage: "$[100-$(vmstat 1 2|tail -1|awk '{print $15}')]"%"
              echo "======"
            done
          background: true
      - run:
          name: Profile CPU and memory every 5s (background)
          command: |
            while true; do
              sleep 5
              printf "\n\n$(date)\n"
              top -b -c -n 1
              echo "======"
            done
          background: true

      - checkout
      - run: 
          name: install some packages
          command: | 
            npm init -y
            npm i express cors
      - run: sleep 45
      - run: |
          cat /sys/fs/cgroup/cpu/cpuacct.usage
          cat /sys/fs/cgroup/memory/memory.usage_in_bytes
workflows:
  main:
    jobs:
      - test_runner
      - test_cloud

executors:
  runner:
    docker:
      - image: cimg/node:lts
    resource_class: ryanpedersen/minikube-nov2022
  cloud:
    docker:
      - image: cimg/node:lts
# VS Code Extension Version: 1.0.0