version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  build:
    executor:
      name: win/default
    steps:
      - run: 
         command: gci env:* | sort-object name
         shell: powershell.exe
workflows:
  test:
    jobs: 
      - build:
          context:
            - envar-test
