version: 2.1
  
jobs:
  build:
    executor:
      name: cloud
      image: "cimg/node:stable"
    steps:
      - checkout
      - run: echo "hello from container-agent"

workflows:
  build-workflow:
    jobs:
      - build

executors:
  cloud:
    parameters:
      image:
        description: "The image you'd like to use"
        default: "cimg/base:stable"
        type: string
    docker:
      - image: <<parameters.image>>
  runner:
    parameters:
      image:
        description: "The image you'd like to use"
        default: "cimg/base:stable"
        type: string
    docker:
      - image: <<parameters.image>>
    resource_class: ryanpedersen/container-agent
