version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1 

jobs:
  generate-config:
    executor: base
    steps:
      - checkout
      - run: 
          name: check tags
          command: |
            echo ${CIRCLE_PULL_REQUEST##*/}

            CONFIG_PATH=".circleci/continuation.yml"

            LABELS=`curl \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues/${CIRCLE_PULL_REQUEST##*/}/labels`
            echo $LABELS | jq -c '.[]' | jq '.name'

     
            if [[ -n ${CIRCLE_PULL_REQUEST##*/} ]]; then
              echo 'export CONFIG_PATH=".circleci/continuation.yml"' >> "$BASH_ENV"
            else
              echo 'export CONFIG_PATH=".circleci/tags/tag.yml"' >> "$BASH_ENV"
            fi

            echo 'export CONFIG_PATH=".circleci/tags/tag.yml"' >> "$BASH_ENV"
      - continuation/continue:
            configuration_path: $CONFIG_PATH

workflows:
  setup-workflow:
    jobs:
      - generate-config

executors:
  base:
    docker:
      - image: cimg/base:stable

# VS Code Extension Version: 1.0.0