version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1 

jobs:
  generate-config:
    executor: base
    steps:
      - run: 
          name: check tags
          command: |
            echo 'export CONFIG_PATH=".circleci/continuation.yml"' >> "$BASH_ENV"
      - continuation/continue:
            configuration_path: $CONFIG_PATH

workflows:
  setup-workflow:
    jobs:
      - generate-config

executors:
  base:
    docker:
      - image: cimg/base:stable

# VS Code Extension Version: 1.0.0