version: 2.1

jobs:
  envar1: 
    parameters: 
      my_env_var: 
        type: env_var_name 
        default: prompt
    executor: base
    steps: 
      - run: 
          name: Check envar
          command: |
            echo ${<< parameters.my_env_var >>}
  envar2:
    executor: base 
    steps: 
      - run: 
          name: Check envar
          command: |
            export my_env_var=$prompt
            echo $my_env_var


workflows:
  test:
    jobs: 
      - envar1: 
          my_env_var: override_envar_here
      - envar2

executors:
  base: 
    docker: 
      - image: cimg/base:stable