version: 2.1
  
jobs:
  test:
    executor: runner
    steps:
      - run:
          name: run usage commands
          command: |
            while true; do
              sleep 5
              echo "Mem Usage: "$(free | grep Mem | awk '{print $3/$2 * 100.0}')"%"
              echo "======"
              echo "CPU Usage: "$[100-$(vmstat 1 2|tail -1|awk '{print $15}')]"%"
              echo "======"
            done
          background: true
          
      - checkout
      - run: 
          name: install node
          command: | 
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - run: sleep 5
      - run: sleep 10

workflows:
  main:
    jobs:
      - test

executors:
  runner:
    docker:
      - image: cimg/base:stable
    resource_class: ryanpedersen/container-runner-local

# VS Code Extension Version: 1.0.0