version: 2.1

jobs:
  main:
    docker:
      - image: cimg/node:lts
    steps:
      # - run: echo "hello" 
      - run: |
          echo << pipeline.parameters.GHA_Event >> << pipeline.parameters.GHA_Meta >>

workflows:
  release:
    # when:
    #   equal: [ "issues", << pipeline.parameters.GHA_Event >>]
    jobs:
      - main

parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""