version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  generate-config:
    executor: base
    steps:
      - checkout
      - run: 
          name: Generate continuation config file
          command: |
            TASK_QUERY=`curl -X GET https://runner.circleci.com/api/v2/tasks?resource-class=ryanpedersen/container-agent -H "Circle-Token: ${API_ACCESS_TOKEN}" | jq .unclaimed_task_count`
            echo $TASK_QUERY
            BUILD_ON=cloud

            MAX_ACCEPTABLE="<<pipeline.parameters.max_acceptable>>"
            
            if [ -z "$TASK_QUERY" ]; then
              echo "export BUILD_ON=cloud" >> $BASH_ENV
            elif [ $TASK_QUERY \> $MAX_ACCEPTABLE]; then
              echo "export BUILD_ON=cloud" >> $BASH_ENV
            else
              BUILD_ON=runner
            fi

            echo $BUILD_ON

            chmod u+x ./scripts/generate-config
            ./scripts/generate-config "$BUILD_ON"
      - continuation/continue:
          configuration_path: configs/generated_config.yml
workflows:
  setup-workflow:
    jobs:
      - generate-config

executors:
  base:
    docker:
      - image: cimg/base:stable

parameters:
  max_acceptable:
    default: 2
    description: |
      high water mark of tasks unclaimed
    type: integer
    