version: 2.1

orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.1.3

jobs:
  yarn_build:
    executor: node
    working_directory: ~/project/subdir
    steps: 
      - checkout
      - node/install-packages: # https://circleci.com/developer/orbs/orb/circleci/node#commands-install-packages
          pkg-manager: yarn

workflows:
  build_test_deploy:
    jobs:
      - yarn_build
      - node/test: # https://circleci.com/developer/orbs/orb/circleci/node#jobs-test
          app-dir: ~/project/subdir
          version: 12.0.0
          pkg-manager: yarn 
          run-command: test:unit
          name: unit_tests
      - node/run: # https://circleci.com/developer/orbs/orb/circleci/node#jobs-run
          app-dir: ~/project/subdir
          version: 12.0.0
          pkg-manager: yarn 
          yarn-run: build
          name: yarn build
          requires: 
            - unit_tests
      - docker/publish: # https://circleci.com/developer/orbs/orb/circleci/docker#jobs-publish
          docker-context: ~/project/subdir
          deploy: true # publish image
          image: test
          # use_remote_docker: true
          # remote_docker_dlc: true # if you want to use built in DLC; can also use cache-from

executors: 
  node:
    docker:
      - image: cimg/node:12.0.0

parameters:
  project-one:
    type: boolean
    default: false