#!/bin/bash 
set -o pipefail

BUILD_ON=$1 # cloud or runner

mkdir configs/
cat << EOF > configs/generated_config.yml
version: 2.1
  
jobs:
  build:
    executor:
      name: $BUILD_ON
      image: cimg/node:current
    steps:
      - checkout
      - run: echo "hello from $BUILD_ON"

workflows:
  build-workflow:
    jobs:
      - build

executors:
  cloud:
    parameters:
      image:
        description: "The image you'd like to use"
        default: "cimg/base:stable"
        type: string
    docker:
      - image: <<parameters.image>>
  runner:
    parameters:
      image:
        description: "The image you'd like to use"
        default: "cimg/base:stable"
        type: string
    docker:
      - image: <<parameters.image>>
    resource_class: ryanpedersen/container-agent
EOF