on:
  issues:
    types: [labeled, unlabeled]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: some_name
        id: some_id
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_SECRET }}